# -*- coding: utf-8 -*-
"""Python_factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuKHRh_eSCLND1Ey-tzL50iAh91dQ29L
"""

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

number = int(input("Enter a number: "))
result = factorial(number)
print(result)